In [2]:
!git status

fatal: not a git repository (or any of the parent directories): .git

In [4]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [6]:
!git --version

git version 2.54.0.windows.1

In [8]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [10]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [12]:
import os

In [14]:
os.getcwd()

'C:\\Users\\Haruna Zakari\\Documents\\AI_Dev_Projects'

In [16]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 5CBA-9528

 Directory of C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

31/05/2026  12:47    <DIR>          .
31/05/2026  12:31    <DIR>          ..
31/05/2026  12:33    <DIR>          .ipynb_checkpoints
29/05/2026  19:45         2,768,680 words_generated.csv
31/05/2026  12:47             3,678 word_count_project.ipynb
               2 File(s)      2,772,358 bytes
               3 Dir(s)  129,520,238,592 bytes free

In [18]:
!git init

Reinitialized existing Git repository in C:/Users/Haruna Zakari/Documents/AI_Dev_Projects/.git/

In [20]:
!git status

On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	words_count_project.ipynb
	words_generated.csv

nothing added to commit but untracked files present (use "git add" to track)

In [22]:
!git add .

In [24]:
!git commit -m "Initial git commit"

On branch main
nothing to commit, working tree clean

In [26]:
!git remote add origin https://github.com/Zacks406/words_count_project

error: remote origin already exists.

In [28]:
!git branch -M main

In [32]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [41]:
import pandas as pd

In [47]:
df = pd.read_csv("enable1.txt", header = None, names = ["words"]);

In [90]:
df["word_count"] = df["words"].str.len()
df

            words  word_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [108]:
df.rename(columns = {"word_count":"char_count"}, inplace = True)

In [109]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [110]:
df["words"] = df["words"].fillna("").astype(str)

In [111]:
def word_value(words):
    return sum(
        ord(char.lower()) - ord("a") + 1
        for char in words
        if char.isalpha()
    )

In [112]:
df["value"] = df["words"].apply(word_value)

In [113]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [114]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [115]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [102]:
!git add .

warning: in the working copy of 'Untitled.ipynb', LF will be replaced by CRLF the next time Git touches it

In [104]:
!git commit -m "Generated char_count and value"

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

In [116]:
!git push

Everything up-to-date

In [119]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [125]:
df["char_count"] = df["char_count"].fillna(0).astype(int)

In [126]:
df["char_count"]

0         2
1         3
2         5
3         6
4         4
         ..
172818    7
172819    9
172820    7
172821    7
172822    8
Name: char_count, Length: 172823, dtype: int64

In [128]:
df

            words  char_count  value
0              aa           2      2
1             aah           3     10
2           aahed           5     19
3          aahing           6     40
4            aahs           4     29
...           ...         ...    ...
172818    zymotic           7    111
172819  zymurgies           9    143
172820    zymurgy           7    135
172821    zyzzyva           7    151
172822   zyzzyvas           8    170

[172823 rows x 3 columns]

In [130]:
df.head()

    words  char_count  value
0      aa           2      2
1     aah           3     10
2   aahed           5     19
3  aahing           6     40
4    aahs           4     29

In [138]:
df.set_index("words")

           char_count  value
words
aa                  2      2
aah                 3     10
aahed               5     19
aahing              6     40
aahs                4     29
...               ...    ...
zymotic             7    111
zymurgies           9    143
zymurgy             7    135
zyzzyva             7    151
zyzzyvas            8    170

[172823 rows x 2 columns]

In [141]:
df.loc["aa"]

KeyError: 'aa'