In [56]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [57]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [58]:
!git --version

git version 2.54.0.windows.1

In [59]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [60]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [61]:
import os

In [62]:
os.getcwd()

'C:\\Users\\Haruna Zakari\\Documents\\AI_Dev_Projects'

In [63]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 5CBA-9528

 Directory of C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

06/06/2026  09:27    <DIR>          .
01/06/2026  16:32    <DIR>          ..
01/06/2026  15:57    <DIR>          .ipynb_checkpoints
29/05/2026  19:19         1,743,363 enable1.txt
29/05/2026  19:19         1,743,363 enable2.txt
01/06/2026  16:17           324,435 Figure_4.1_Bathymetry.png
01/06/2026  15:43            14,191 Figure_4.7_CS01_Velocity.png
31/05/2026  19:41            11,560 Untitled.ipynb
01/06/2026  15:43            28,933 Untitled1.ipynb
01/06/2026  15:57            19,497 Untitled2.ipynb
01/06/2026  16:17             4,157 Untitled3.ipynb
31/05/2026  12:49             4,721 words_count_project.ipynb
29/05/2026  19:45         2,768,680 words_generated.csv
06/06/2026  09:27            52,428 word_count_project.ipynb
              11 File(s)      6,715,328 bytes
               3 Dir(s)  130,186,153,984 bytes free

In [64]:
!git init

Reinitialized existing Git repository in C:/Users/Haruna Zakari/Documents/AI_Dev_Projects/.git/

In [65]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [66]:
!git add .

warning: in the working copy of 'word_count_project.ipynb', LF will be replaced by CRLF the next time Git touches it

In [67]:
!git commit -m "Initial git commit"

[main ae74f8a] Initial git commit
 1 file changed, 98 insertions(+), 360 deletions(-)

In [68]:
!git remote add origin https://github.com/Zacks406/words_count_project

error: remote origin already exists.

In [69]:
!git branch -M main

In [70]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

To https://github.com/Zacks406/words_count_project
   661118c..ae74f8a  main -> main

In [71]:
import pandas as pd

In [72]:
df = pd.read_csv("enable1.txt", header = None, names = ["words"]);

In [73]:
df["word_count"] = df["words"].str.len()
df

            words  word_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [74]:
df.rename(columns = {"word_count":"char_count"}, inplace = True)

In [75]:
df

            words  char_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [76]:
df["words"] = df["words"].fillna("").astype(str)

In [77]:
def word_value(words):
    return sum(
        ord(char.lower()) - ord("a") + 1
        for char in words
        if char.isalpha()
    )

In [78]:
df["value"] = df["words"].apply(word_value)

In [79]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [80]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [81]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [82]:
!git add .

In [83]:
!git commit -m "Generated char_count and value"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [84]:
!git push

Everything up-to-date

In [85]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [86]:
df["char_count"] = df["char_count"].fillna(0).astype(int)

In [87]:
df["value"] = df["value"].fillna(0).astype(int)

In [88]:
df["value"]

0           2
1          10
2          19
3          40
4          29
         ...
172818    111
172819    143
172820    135
172821    151
172822    170
Name: value, Length: 172823, dtype: int64

In [89]:
df["char_count"]

0         2
1         3
2         5
3         6
4         4
         ..
172818    7
172819    9
172820    7
172821    7
172822    8
Name: char_count, Length: 172823, dtype: int64

In [90]:
df

            words  char_count  value
0              aa           2      2
1             aah           3     10
2           aahed           5     19
3          aahing           6     40
4            aahs           4     29
...           ...         ...    ...
172818    zymotic           7    111
172819  zymurgies           9    143
172820    zymurgy           7    135
172821    zyzzyva           7    151
172822   zyzzyvas           8    170

[172823 rows x 3 columns]

In [91]:
df.head()

    words  char_count  value
0      aa           2      2
1     aah           3     10
2   aahed           5     19
3  aahing           6     40
4    aahs           4     29

In [92]:
df = df.set_index("words")

In [93]:
df.loc["aahed"]

char_count     5
value         19
Name: aahed, dtype: int64

In [94]:
df.info()

<class 'pandas.DataFrame'>
Index: 172823 entries, aa to zyzzyvas
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   char_count  172823 non-null  int64
 1   value       172823 non-null  int64
dtypes: int64(2)
memory usage: 8.0+ MB

In [95]:
df.loc["pandas"]

char_count     6
value         55
Name: pandas, dtype: int64

In [96]:
df.loc["pandas", "value"]

np.int64(55)

In [97]:
df.shape

(172823, 2)

In [98]:
df.max()

char_count     28
value         319
dtype: int64

In [99]:
df["value"].max()

np.int64(319)

In [100]:
df.describe()

          char_count          value
count  172823.000000  172823.000000
mean        9.087523     107.752932
std         2.818439      39.318933
min         0.000000       0.000000
25%         7.000000      80.000000
50%         9.000000     103.000000
75%        11.000000     131.000000
max        28.000000     319.000000

In [101]:
df.loc[["pinfish", "glowing", "enfold", "microbrew"]]

           char_count  value
words
pinfish             7     81
glowing             7     87
enfold              6     56
microbrew           9    106

In [102]:
df.loc[["pinfish", "glowing", "enfold", "microbrew"], "value"]

words
pinfish       81
glowing       87
enfold        56
microbrew    106
Name: value, dtype: int64

In [103]:
df.sort_values(by="value", ascending = False)

                          char_count  value
words
reinstitutionalizations           23    319
microspectrophotometries          24    317
microspectrophotometry            22    309
microspectrophotometers           23    308
otorhinolaryngologists            22    307
...                              ...    ...
ab                                 2      3
ba                                 2      3
aa                                 2      2
                                   0      0
                                   0      0

[172823 rows x 2 columns]

In [104]:
df.loc[df["value"] == 319]

                         char_count  value
words
reinstitutionalizations          23    319

In [105]:
[df["value"] == 319]

[words
 aa           False
 aah          False
 aahed        False
 aahing       False
 aahs         False
              ...
 zymotic      False
 zymurgies    False
 zymurgy      False
 zyzzyva      False
 zyzzyvas     False
 Name: value, Length: 172823, dtype: bool]

In [106]:
for row in df:
    if row["value"] == 319:
        print(row)

TypeError: string indices must be integers, not 'str'

In [111]:
df.describe()

          char_count          value
count  172823.000000  172823.000000
mean        9.087523     107.752932
std         2.818439      39.318933
min         0.000000       0.000000
25%         7.000000      80.000000
50%         9.000000     103.000000
75%        11.000000     131.000000
max        28.000000     319.000000

In [112]:
df["value"].mode()

0    93
Name: value, dtype: int64

In [113]:
df.head()

        char_count  value
words
aa               2      2
aah              3     10
aahed            5     19
aahing           6     40
aahs             4     29

In [114]:
df["value"].value_counts().head()

value
93     1965
100    1921
95     1915
99     1907
92     1902
Name: count, dtype: int64

In [ ]:
df.loc[df["value"] == 93].head()

In [ ]:
df[df["value"] == 93].sample(10)

In [ ]:
df.loc[df["value"] == 274].sort_values(by = "char_count", ascending = True)

In [ ]:
df.loc[df["value"] == 274, "char_count"].min()

In [116]:
df.loc[
    (df["value"] == 274) & (df["char_count"] == 20)
    ]

                      char_count  value
words
overprotectivenesses          20    274

In [117]:
df.info()

<class 'pandas.DataFrame'>
Index: 172823 entries, aa to zyzzyvas
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   char_count  172823 non-null  int64
 1   value       172823 non-null  int64
dtypes: int64(2)
memory usage: 8.0+ MB

In [118]:
df.head()

        char_count  value
words
aa               2      2
aah              3     10
aahed            5     19
aahing           6     40
aahs             4     29

In [120]:
df["ratio"] = (df["value"]) / (df["char_count"])

In [121]:
df["ratio"].head()

words
aa        1.000000
aah       3.333333
aahed     3.800000
aahing    6.666667
aahs      7.250000
Name: ratio, dtype: float64

In [122]:
df["ratio"].max()

np.float64(22.5)

In [123]:
df["ratio"].min()

np.float64(1.0)

In [124]:
df["ratio"].info()

<class 'pandas.Series'>
Index: 172823 entries, aa to zyzzyvas
Series name: ratio
Non-Null Count   Dtype
--------------   -----
172821 non-null  float64
dtypes: float64(1)
memory usage: 6.7+ MB

In [125]:
df.sort_values(by = "ratio", ascending = False).head()

       char_count  value      ratio
words
xu              2     45  22.500000
muzzy           5    111  22.200000
wry             3     66  22.000000
xyst            4     88  22.000000
pyx             3     65  21.666667

In [126]:
df.loc[df["ratio"] == df["ratio"].max()]

       char_count  value  ratio
words
xu              2     45   22.5

In [130]:
df.loc[df["ratio"] == 10]

            char_count  value  ratio
words
aardwolf             8     80   10.0
abatements          10    100   10.0
abducts              7     70   10.0
abetment             8     80   10.0
abettals             8     80   10.0
...                ...    ...    ...
ycleped              7     70   10.0
yodeled              7     70   10.0
zamia                5     50   10.0
zebecs               6     60   10.0
zwieback             8     80   10.0

[2604 rows x 3 columns]

In [147]:
df.loc[df["ratio"] == 10].shape

(2604, 3)

In [151]:
df.query("ratio == 10").shape

(2604, 3)

In [155]:
df.query("ratio == 10").sort_values(by = "value", ascending = False)

                          char_count  value  ratio
words
electrocardiographically          24    240   10.0
electroencephalographies          24    240   10.0
electroencephalographer           23    230   10.0
electrodesiccation                18    180   10.0
chemiluminescences                18    180   10.0
...                              ...    ...    ...
day                                3     30   10.0
bug                                3     30   10.0
web                                3     30   10.0
as                                 2     20   10.0
oe                                 2     20   10.0

[2604 rows x 3 columns]

In [165]:
df.loc[df["ratio"] == 10, "value"].max()

np.int64(240)

In [167]:
df.loc[df["value"] == 260, "char_count"]

words
countermobilizations    20
hydroxytryptamine       17
neuropsychologists      18
psychophysiologist      18
revolutionarinesses     19
underrepresentations    20
Name: char_count, dtype: int64

In [168]:
df.loc[df["value"] == 260, "char_count"].min()

np.int64(17)

In [171]:
mean_char_count = df["char_count"].mean()
mean_char_count

np.float64(9.087523072739161)

In [176]:
df.query("`char_count` > @mean_char_count")

              char_count  value      ratio
words
aardwolves            10    120  12.000000
abacterial            10     72   7.200000
abandoners            10     93   9.300000
abandoning            10     81   8.100000
abandonment           11    103   9.363636
...                  ...    ...        ...
zygomorphies          12    176  14.666667
zygomorphy            10    168  16.800000
zygosities            10    154  15.400000
zygospores            10    165  16.500000
zymologies            10    146  14.600000

[67582 rows x 3 columns]