In [1]:
!git status

On branch main
Your branch is ahead of 'origin/main' by 2 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .ipynb_checkpoints/word_count_project-checkpoint.ipynb
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [2]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [3]:
!git --version

git version 2.54.0.windows.1

In [4]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [5]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [6]:
import os

In [7]:
os.getcwd()

'C:\\Users\\Haruna Zakari\\Documents\\AI_Dev_Projects'

In [8]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 5CBA-9528

 Directory of C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

03/06/2026  11:36    <DIR>          .
01/06/2026  16:32    <DIR>          ..
01/06/2026  15:57    <DIR>          .ipynb_checkpoints
29/05/2026  19:19         1,743,363 enable1.txt
29/05/2026  19:19         1,743,363 enable2.txt
01/06/2026  16:17           324,435 Figure_4.1_Bathymetry.png
01/06/2026  15:43            14,191 Figure_4.7_CS01_Velocity.png
31/05/2026  19:41            11,560 Untitled.ipynb
01/06/2026  15:43            28,933 Untitled1.ipynb
01/06/2026  15:57            19,497 Untitled2.ipynb
01/06/2026  16:17             4,157 Untitled3.ipynb
31/05/2026  12:49             4,721 words_count_project.ipynb
29/05/2026  19:45         2,768,680 words_generated.csv
03/06/2026  11:36            59,035 word_count_project.ipynb
              11 File(s)      6,721,935 bytes
               3 Dir(s)  131,001,274,368 bytes free

In [9]:
!git init

Reinitialized existing Git repository in C:/Users/Haruna Zakari/Documents/AI_Dev_Projects/.git/

In [10]:
!git status

On branch main
Your branch is ahead of 'origin/main' by 2 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .ipynb_checkpoints/word_count_project-checkpoint.ipynb
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [11]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/word_count_project-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'word_count_project.ipynb', LF will be replaced by CRLF the next time Git touches it

In [12]:
!git commit -m "Initial git commit"

[main 4ddd642] Initial git commit
 2 files changed, 2568 insertions(+), 123 deletions(-)

In [13]:
!git remote add origin https://github.com/Zacks406/words_count_project

error: remote origin already exists.

In [14]:
!git branch -M main

In [15]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

To https://github.com/Zacks406/words_count_project
   841a1af..4ddd642  main -> main

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("enable1.txt", header = None, names = ["words"]);

In [18]:
df["word_count"] = df["words"].str.len()
df

            words  word_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [19]:
df.rename(columns = {"word_count":"char_count"}, inplace = True)

In [20]:
df

            words  char_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [21]:
df["words"] = df["words"].fillna("").astype(str)

In [22]:
def word_value(words):
    return sum(
        ord(char.lower()) - ord("a") + 1
        for char in words
        if char.isalpha()
    )

In [23]:
df["value"] = df["words"].apply(word_value)

In [24]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [25]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [26]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [27]:
!git add .

In [28]:
!git commit -m "Generated char_count and value"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [29]:
!git push

Everything up-to-date

In [30]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [95]:
df["char_count"] = df["char_count"].fillna(0).astype(int)

In [ ]:
df["ch"] = df["char_count"].fillna(0).astype(int)

In [32]:
df["char_count"]

0         2
1         3
2         5
3         6
4         4
         ..
172818    7
172819    9
172820    7
172821    7
172822    8
Name: char_count, Length: 172823, dtype: int64

In [33]:
df

            words  char_count  value
0              aa           2      2
1             aah           3     10
2           aahed           5     19
3          aahing           6     40
4            aahs           4     29
...           ...         ...    ...
172818    zymotic           7    111
172819  zymurgies           9    143
172820    zymurgy           7    135
172821    zyzzyva           7    151
172822   zyzzyvas           8    170

[172823 rows x 3 columns]

In [34]:
df.head()

    words  char_count  value
0      aa           2      2
1     aah           3     10
2   aahed           5     19
3  aahing           6     40
4    aahs           4     29

In [35]:
df = df.set_index("words")

In [36]:
df.loc["aahed"]

char_count     5
value         19
Name: aahed, dtype: int64

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 172823 entries, aa to zyzzyvas
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   char_count  172823 non-null  int64
 1   value       172823 non-null  int64
dtypes: int64(2)
memory usage: 8.0+ MB

In [38]:
df.loc["pandas"]

char_count     6
value         55
Name: pandas, dtype: int64

In [39]:
df.loc["pandas", "value"]

np.int64(55)

In [40]:
df.shape

(172823, 2)

In [41]:
df.max()

char_count     28
value         319
dtype: int64

In [42]:
df["value"].max()

np.int64(319)

In [43]:
df.describe()

          char_count          value
count  172823.000000  172823.000000
mean        9.087523     107.752932
std         2.818439      39.318933
min         0.000000       0.000000
25%         7.000000      80.000000
50%         9.000000     103.000000
75%        11.000000     131.000000
max        28.000000     319.000000

In [44]:
df.loc[["pinfish", "glowing", "enfold", "microbrew"]]

           char_count  value
words
pinfish             7     81
glowing             7     87
enfold              6     56
microbrew           9    106

In [45]:
df.loc[["pinfish", "glowing", "enfold", "microbrew"], "value"]

words
pinfish       81
glowing       87
enfold        56
microbrew    106
Name: value, dtype: int64

In [46]:
df.sort_values(by="value", ascending = False)

                          char_count  value
words
reinstitutionalizations           23    319
microspectrophotometries          24    317
microspectrophotometry            22    309
microspectrophotometers           23    308
otorhinolaryngologists            22    307
...                              ...    ...
ab                                 2      3
ba                                 2      3
aa                                 2      2
                                   0      0
                                   0      0

[172823 rows x 2 columns]

In [47]:
df.loc[df["value"] == 319]

                         char_count  value
words
reinstitutionalizations          23    319

In [48]:
[df["value"] == 319]

[words
 aa           False
 aah          False
 aahed        False
 aahing       False
 aahs         False
              ...
 zymotic      False
 zymurgies    False
 zymurgy      False
 zyzzyva      False
 zyzzyvas     False
 Name: value, Length: 172823, dtype: bool]

In [49]:
for row in df:
    if row["value"] == 319:
        print(row)

TypeError: string indices must be integers, not 'str'

In [ ]:
df.describe()

In [ ]:
df["value"].mode()

In [ ]:
df.head()

In [ ]:
df["value"].value_counts().head()

In [ ]:
df.loc[df["value"] == 93].head()

In [50]:
df[df["value"] == 93].sample(10)

             char_count  value
words
touraco               7     93
megalomanic          11     93
whirler               7     93
puslike               7     93
hairpieces           10     93
phenazin              8     93
disseised             9     93
tangelos              8     93
awnless               7     93
sylphid               7     93

In [67]:
df.loc[df["value"] == 274].sort_values(by = "char_count", ascending = True)

                       char_count  value
words
overprotectivenesses           20    274
countercountermeasure          21    274
psychophysiologically          21    274

In [77]:
df.loc[df["value"] == 274, "char_count"].min()

np.int64(20)

In [85]:
df.loc[
    (df["value"] == 274) & (df["char_count"] == 20)
    ]

                      char_count  value
words
overprotectivenesses          20    274

In [92]:
df.info()

<class 'pandas.DataFrame'>
Index: 172823 entries, aa to zyzzyvas
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   char_count  172823 non-null  int64
 1   value       172823 non-null  int64
dtypes: int64(2)
memory usage: 8.0+ MB

In [93]:
df.loc["word_value_ratio"] = df[
    (df["value"]) / (df["char_count"])
]

KeyError: "None of [Index([               1.0, 3.3333333333333335,                3.8,\n        6.666666666666667,               7.25,  4.666666666666667,\n                      6.4,                8.5,               8.25,\n                      9.5,\n       ...\n                    17.25, 16.142857142857142,               16.5,\n       17.428571428571427,               18.0, 15.857142857142858,\n        15.88888888888889, 19.285714285714285, 21.571428571428573,\n                    21.25],\n      dtype='float64', length=172823)] are in the [columns]"