In [99]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .ipynb_checkpoints/word_count_project-checkpoint.ipynb
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [100]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [101]:
!git --version

git version 2.54.0.windows.1

In [102]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.

In [103]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [104]:
import os

In [105]:
os.getcwd()

'C:\\Users\\Haruna Zakari\\Documents\\AI_Dev_Projects'

In [106]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 5CBA-9528

 Directory of C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

03/06/2026  18:17    <DIR>          .
01/06/2026  16:32    <DIR>          ..
01/06/2026  15:57    <DIR>          .ipynb_checkpoints
29/05/2026  19:19         1,743,363 enable1.txt
29/05/2026  19:19         1,743,363 enable2.txt
01/06/2026  16:17           324,435 Figure_4.1_Bathymetry.png
01/06/2026  15:43            14,191 Figure_4.7_CS01_Velocity.png
31/05/2026  19:41            11,560 Untitled.ipynb
01/06/2026  15:43            28,933 Untitled1.ipynb
01/06/2026  15:57            19,497 Untitled2.ipynb
01/06/2026  16:17             4,157 Untitled3.ipynb
31/05/2026  12:49             4,721 words_count_project.ipynb
29/05/2026  19:45         2,768,680 words_generated.csv
03/06/2026  18:17            63,161 word_count_project.ipynb
              11 File(s)      6,726,061 bytes
               3 Dir(s)  130,987,102,208 bytes free

In [107]:
!git init

Reinitialized existing Git repository in C:/Users/Haruna Zakari/Documents/AI_Dev_Projects/.git/

In [108]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .ipynb_checkpoints/word_count_project-checkpoint.ipynb
	modified:   word_count_project.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [109]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/word_count_project-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'word_count_project.ipynb', LF will be replaced by CRLF the next time Git touches it

In [110]:
!git commit -m "Initial git commit"

[main 4ec9b48] Initial git commit
 2 files changed, 641 insertions(+), 410 deletions(-)

In [111]:
!git remote add origin https://github.com/Zacks406/words_count_project

error: remote origin already exists.

In [112]:
!git branch -M main

In [113]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

To https://github.com/Zacks406/words_count_project
   4ddd642..4ec9b48  main -> main

In [114]:
import pandas as pd

In [115]:
df = pd.read_csv("enable1.txt", header = None, names = ["words"]);

In [116]:
df["word_count"] = df["words"].str.len()
df

            words  word_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [117]:
df.rename(columns = {"word_count":"char_count"}, inplace = True)

In [118]:
df

            words  char_count
0              aa         2.0
1             aah         3.0
2           aahed         5.0
3          aahing         6.0
4            aahs         4.0
...           ...         ...
172818    zymotic         7.0
172819  zymurgies         9.0
172820    zymurgy         7.0
172821    zyzzyva         7.0
172822   zyzzyvas         8.0

[172823 rows x 2 columns]

In [119]:
df["words"] = df["words"].fillna("").astype(str)

In [120]:
def word_value(words):
    return sum(
        ord(char.lower()) - ord("a") + 1
        for char in words
        if char.isalpha()
    )

In [121]:
df["value"] = df["words"].apply(word_value)

In [122]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [123]:
!cd

C:\Users\Haruna Zakari\Documents\AI_Dev_Projects

In [124]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [125]:
!git add .

In [126]:
!git commit -m "Generated char_count and value"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [127]:
!git push

Everything up-to-date

In [128]:
df

            words  char_count  value
0              aa         2.0      2
1             aah         3.0     10
2           aahed         5.0     19
3          aahing         6.0     40
4            aahs         4.0     29
...           ...         ...    ...
172818    zymotic         7.0    111
172819  zymurgies         9.0    143
172820    zymurgy         7.0    135
172821    zyzzyva         7.0    151
172822   zyzzyvas         8.0    170

[172823 rows x 3 columns]

In [129]:
df["char_count"] = df["char_count"].fillna(0).astype(int)

In [130]:
df["value"] = df["value"].fillna(0).astype(int)

In [131]:
df["value"]

0           2
1          10
2          19
3          40
4          29
         ...
172818    111
172819    143
172820    135
172821    151
172822    170
Name: value, Length: 172823, dtype: int64

In [132]:
df["char_count"]

0         2
1         3
2         5
3         6
4         4
         ..
172818    7
172819    9
172820    7
172821    7
172822    8
Name: char_count, Length: 172823, dtype: int64

In [133]:
df

            words  char_count  value
0              aa           2      2
1             aah           3     10
2           aahed           5     19
3          aahing           6     40
4            aahs           4     29
...           ...         ...    ...
172818    zymotic           7    111
172819  zymurgies           9    143
172820    zymurgy           7    135
172821    zyzzyva           7    151
172822   zyzzyvas           8    170

[172823 rows x 3 columns]

In [134]:
df.head()

    words  char_count  value
0      aa           2      2
1     aah           3     10
2   aahed           5     19
3  aahing           6     40
4    aahs           4     29

In [135]:
df = df.set_index("words")

In [136]:
df.loc["aahed"]

char_count     5
value         19
Name: aahed, dtype: int64

In [137]:
df.info()

<class 'pandas.DataFrame'>
Index: 172823 entries, aa to zyzzyvas
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   char_count  172823 non-null  int64
 1   value       172823 non-null  int64
dtypes: int64(2)
memory usage: 8.0+ MB

In [138]:
df.loc["pandas"]

char_count     6
value         55
Name: pandas, dtype: int64

In [139]:
df.loc["pandas", "value"]

np.int64(55)

In [140]:
df.shape

(172823, 2)

In [141]:
df.max()

char_count     28
value         319
dtype: int64

In [142]:
df["value"].max()

np.int64(319)

In [143]:
df.describe()

          char_count          value
count  172823.000000  172823.000000
mean        9.087523     107.752932
std         2.818439      39.318933
min         0.000000       0.000000
25%         7.000000      80.000000
50%         9.000000     103.000000
75%        11.000000     131.000000
max        28.000000     319.000000

In [144]:
df.loc[["pinfish", "glowing", "enfold", "microbrew"]]

           char_count  value
words
pinfish             7     81
glowing             7     87
enfold              6     56
microbrew           9    106

In [145]:
df.loc[["pinfish", "glowing", "enfold", "microbrew"], "value"]

words
pinfish       81
glowing       87
enfold        56
microbrew    106
Name: value, dtype: int64

In [146]:
df.sort_values(by="value", ascending = False)

                          char_count  value
words
reinstitutionalizations           23    319
microspectrophotometries          24    317
microspectrophotometry            22    309
microspectrophotometers           23    308
otorhinolaryngologists            22    307
...                              ...    ...
ab                                 2      3
ba                                 2      3
aa                                 2      2
                                   0      0
                                   0      0

[172823 rows x 2 columns]

In [147]:
df.loc[df["value"] == 319]

                         char_count  value
words
reinstitutionalizations          23    319

In [148]:
[df["value"] == 319]

[words
 aa           False
 aah          False
 aahed        False
 aahing       False
 aahs         False
              ...
 zymotic      False
 zymurgies    False
 zymurgy      False
 zyzzyva      False
 zyzzyvas     False
 Name: value, Length: 172823, dtype: bool]

In [149]:
for row in df:
    if row["value"] == 319:
        print(row)

TypeError: string indices must be integers, not 'str'

In [ ]:
df.describe()

In [ ]:
df["value"].mode()

In [ ]:
df.head()

In [ ]:
df["value"].value_counts().head()

In [ ]:
df.loc[df["value"] == 93].head()

In [ ]:
df[df["value"] == 93].sample(10)

In [150]:
df.loc[df["value"] == 274].sort_values(by = "char_count", ascending = True)

                       char_count  value
words
overprotectivenesses           20    274
countercountermeasure          21    274
psychophysiologically          21    274

In [151]:
df.loc[df["value"] == 274, "char_count"].min()

np.int64(20)

In [152]:
df.loc[
    (df["value"] == 274) & (df["char_count"] == 20)
    ]

                      char_count  value
words
overprotectivenesses          20    274

In [ ]:
df.info()

In [158]:
df.loc["word_value_ratio"] =  df["value"] / df["char_count"]

SyntaxError: invalid syntax (2612283559.py, line 1)